### ISSUE TITLE
Wrong types for some properties

### ISSUE THREAD

**Issue by jck** [emersion/mpris-service#1]
Using the latest version,

```
(playerctl:16525): GLib-GIO-WARNING **: Received property Rate with type y does not match expected type d in the expected interface

(playerctl:16525): GLib-GIO-WARNING **: Received property Volume with type y does not match expected type d in the expected interface

(playerctl:16525): GLib-GIO-WARNING **: Received property Position with type y does not match expected type x in the expected interface

(playerctl:16525): GLib-GIO-WARNING **: Received property MinimumRate with type y does not match expected type d in the expected interface

(playerctl:16525): GLib-GIO-WARNING **: Received property MaximumRate with type y does not match expected type d in the expected interface
```

**Comment by emersion** [comment]
I cannot reproduce... Can you provide your source code please?

**Comment by jck** [comment]
Here it is: https://github.com/twolfson/google-music-electron/blob/master/lib/mpris.js

**Comment by emersion** [comment]
And does the player works properly? Is there a problem with volume or position?

**Comment by jck** [comment]
The player works properly. The problem is that client's cannot access Rate because it does not match the expected type.

**Comment by emersion** [comment]
Can you check with the latest version please?

I cannot reproduce with GNOME 3.16.

**Comment by pezam** [comment]
I looked into this some time ago, as far as I understood, the problem is node-dbus and the way it tries to intelligently convert JavaScripts float64 into different types, which is happening here https://github.com/Shouqun/node-dbus/blob/master/src/encoder.cc#L28-52
It doesn't seem to care about the type you specify, it just looks at the values. The Byte detection code
```
if(number >= 0 && number <= 255) {
```
eats all of your values, causing them to become type y in dbus.

**Comment by jck** [comment]
@pezam , I noticed that you made some changes to the file you mentioned in node-dbus. Did you fix the issue?

**Comment by pezam** [comment]
No, sorry, that doesn't fix the type y issue, fixed another one that occured before. Type y would take way more work than that

**Comment by jostrander** [comment]
I was going to open a new issue, however this one almost matches the description entirely. Currently facing a bug where the Metadata 'mpris:length' is expected to be an int64 (type x), but is currently marshalled to uint32. I've spent the better half of my morning diving into node-dbus only to figure out that the signal is only 'a{sv}', where v is the metadata object, and there's no way to provide signatures for each property in the metadata. Is this something you can see that would be fixable maybe via 'on the fly' instrospection?

**Comment by emersion** [comment]
Seems that this code is here: https://github.com/Shouqun/node-dbus/blob/master/src/encoder.cc#L80

**Comment by jostrander** [comment]
Yeah, I've opened an issue in that repo for this as well, and I thought we had solved it, but then I went to implement and it didn't work, which lead me to this issue. I'll explain what I found on that one over there and see if they might be able to troubleshoot some more.

**Comment by fcastilloec** [comment]
Has there been any progress on this? I can't get the position of my track because it's the wrong type.
I have a work around for `rate`, `minimumRate` and `maximumRate`, since my app can't have different rates and should be always 1, I store it as `rate=1+1e-15` and the same for the other ones. This prevents it from being stored as `byte` and for `mpris` it's shown as a 1
But there's nothing that I've come up with that can store something as type x (int 64), any ideas?
